# Generated by Django 4.2.4 on 2023-09-19 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz_management', '0003_alter_quizattempter_quiz_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=120)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.question')),
                ('quiz_attempter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quizattempter')),
            ],
        ),
    ]
