# Generated by Django 4.2.5 on 2023-09-26 12:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz_management', '0001_initial'),
        ('quiz_attempter_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quiz'),
        ),
        migrations.AddField(
            model_name='mark',
            name='quiz_attempter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quizattempter'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quiz'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='quiz_attempter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quizattempter'),
        ),
        migrations.AddField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_attempter_management.discussion'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quiz'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quiz_attempter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quizattempter'),
        ),
    ]
