# Generated by Django 4.2.4 on 2023-09-19 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0003_alter_quizattempter_quiz_id'),
        ('quiz_attempter_management', '0002_alter_answer_quiz_attempter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.question'),
        ),
    ]
