# Generated by Django 4.2.4 on 2023-09-23 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0001_initial'),
        ('quiz_attempter_management', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='quiz_attempter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quizattempter'),
        ),
    ]
