# Generated by Django 4.2.4 on 2023-09-20 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0003_alter_quizattempter_quiz_id'),
        ('quiz_attempter_management', '0004_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quiz'),
        ),
    ]
