# Generated by Django 4.2.5 on 2023-09-20 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0003_alter_quizattempter_quiz_id'),
        ('quiz_attempter_management', '0005_alter_mark_quiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('details', models.TextField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quiz')),
                ('quiz_attempter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quizattempter')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quizattempter')),
                ('discussion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_attempter_management.discussion')),
            ],
        ),
    ]
