# Generated by Django 4.2.4 on 2023-09-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempter',
            name='is_quiz_attempter',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
