# Generated by Django 4.2.5 on 2023-09-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
