# Generated by Django 4.2.5 on 2023-09-24 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0002_alter_quiz_end_time_alter_quiz_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttemptersExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AddField(
            model_name='quizattempter',
            name='excel_file',
            field=models.FileField(blank=True, null=True, upload_to='quiz_attempters_excel_files/'),
        ),
    ]
