# Generated by Django 4.2.4 on 2023-09-18 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0002_quizattempter_is_quiz_attempter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempter',
            name='quiz_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz_management.quiz'),
        ),
    ]
