# Generated by Django 4.2.5 on 2023-09-24 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0003_quizattemptersexcel_quizattempter_excel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempter',
            name='excel_file',
        ),
    ]
