# Generated by Django 4.2.5 on 2023-09-21 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0003_alter_quizattempter_quiz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempter',
            name='is_first_time_login',
            field=models.BooleanField(default=True),
        ),
    ]
