# Generated by Django 4.2.5 on 2023-09-15 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0003_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.JSONField(default='What is OOP'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=120),
        ),
    ]
