# Generated by Django 4.2.5 on 2023-09-21 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0004_quizattempter_is_first_time_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempter',
            name='quiz_id',
        ),
        migrations.AddField(
            model_name='quizattempter',
            name='quiz_id',
            field=models.ManyToManyField(to='quiz_management.quiz'),
        ),
    ]
