# Generated by Django 4.2.5 on 2023-09-15 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_management', '0004_question_answer_alter_question_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_marks',
            new_name='marks',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer',
            new_name='question_details',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question',
        ),
    ]
